export const categories = [
    { id: 1064, name: "Anticaspa" },
    { id: 1065, name: "Antimanchas" },
    { id: 1066, name: "Cicatrizantes" },
    { id: 1067, name: "Nutricosméticos" },
    { id: 1068, name: "Control de peso" },
    { id: 1069, name: "Antiacné" },
    { id: 1070, name: "Desodorante" },
    { id: 1090, name: "Medicina bioreguladora" },
    { id: 1091, name: "Suplementos" },
    { id: 1092, name: "Homeopáticos" },
    { id: 1195, name: "Tarjeta de regalo" },
    { id: 150, name: "Limpieza" },
    { id: 153, name: "Hidratación y nutritiva" },
    { id: 154, name: "Tónico" },
    { id: 155, name: "Contorno de ojos" },
    { id: 158, name: "Protección solar" },
    { id: 159, name: "Antioxidante" },
    { id: 160, name: "Antimanchas" }, ,
    { id: 161, name: "Antiedad" },
    { id: 162, name: "Antiacné" },
    { id: 164, name: "Concentrado" },
    { id: 165, name: "Mascarilla" },
    { id: 166, name: "Exfoliante" },
    { id: 17, name: "Sin categoria" },
    { id: 322, name: "Peeling" },
    { id: 330, name: "Cuello y escote" },
    { id: 333, name: "Facial" },
    { id: 334, name: "Maquillaje" },
    { id: 335, name: "Rostro" },
    { id: 336, name: "Antiedad" },
    { id: 371, name: "Manos" },
    { id: 397, name: "Antimanchas" },
    { id: 404, name: "Base" },
    { id: 405, name: "Antiacné" },
    { id: 412, name: "Pestaña y cejas" },
    { id: 415, name: "Capilar" },
    { id: 416, name: "Shampoo" },
    { id: 423, name: "Tratamiento" },
    { id: 427, name: "Corporal" },
    { id: 430, name: "Hidratación y nutritiva" },
    { id: 435, name: "Labios" },
    { id: 436, name: "Labiales" },
    { id: 438, name: "Reafirmante" },
    { id: 439, name: "Antiedad" },
    { id: 450, name: "Anticelulitis" },
    { id: 451, name: "Primer" },
    { id: 456, name: "Polvo" },
    { id: 475, name: "Labios" },
    { id: 476, name: "Brillos" },
    { id: 477, name: "Antiedad" },
    { id: 485, name: "Corrector" },
    { id: 487, name: "Paleta facial" },
    { id: 489, name: "Rubor" },
    { id: 491, name: "Ojos" },
    { id: 492, name: "Pestañina" },
    { id: 493, name: "Iluminador" },
    { id: 498, name: "Delineador" },
    { id: 499, name: "Sombras" },
    { id: 508, name: "Acondicionador" },
    { id: 509, name: "Anticaída" },
    { id: 510, name: "Desmaquillante" },
    { id: 511, name: "Contouring" },
    { id: 512, name: "Bronzer" },
    { id: 513, name: "Limpieza" },
    { id: 514, name: "Exfoliante" },
    { id: 515, name: "Factor de protección solar" },
    { id: 657, name: "Cejas" },
]